### ISSUE TITLE
Responsive CSS

### ISSUE THREAD

**Issue by cosola** [cosola-salvia/macile-newsletter#1]
Maria Rosa to write responsive CSS for newsletter. Dr. V.

**Comment by Morban15** [comment]
When I try to push, happen this:

> remote: Permission to cosola-salvia/macile-newsletter.git denied to Morban18.
> fatal: unable to access 'https://github.com/cosola-salvia/macile-newsletter.git/': The requested URL returned error: 403

**Comment by cosola** [comment]
OK will review.  Did you create a new branch? Did you push to the branch?

Dr. V.

SClaudina Vargas, Ph.D.
Complex Systems Optimization Lab
P.O. Box 1087
Northampton, MA 01060
(413) 387-0161
E-Mail: scvargas@cosola.org
MACILE: www.macile.org
www.cosola.org

**Comment by cosola** [comment]
Maria Rosa,

Read the information provided here for the same issue;  try implementing
some of the suggestions. Let me know if the error persists.

https://stackoverflow.com/questions/51231996/git-returning-error-403-while-pushing-the-code

Have a great weekend,


Dr. Vargas

SClaudina Vargas, Ph.D.
Complex Systems Optimization Lab
P.O. Box 1087
Northampton, MA 01060
(413) 387-0161
E-Mail: scvargas@cosola.org
MACILE: www.macile.org
www.cosola.org

**Comment by Morban15** [comment]
I tried, but the problem continue

> $ git push origin newsletter-rwd
remote: Permission to cosola-salvia/macile-newsletter.git denied to Morban15.
fatal: unable to access 'https://github.com/cosola-salvia/macile-newsletter.git/': The requested URL returned error: 403

**Comment by Morban15** [comment]
Reviews completed @cosola

**Comment by misscs** [comment]
This issue appears to be resolved. I'm going to close it. 💃
