### ISSUE TITLE
Implement landing page header

### ISSUE THREAD

**Issue by misscs** [cosola-salvia/macile-newsletter#115]
For mobile, stack the about section under the header.

<img width="680" alt="Screen Shot 2020-05-12 at 11 49 41" src="https://user-images.githubusercontent.com/51812/81715868-b6941100-9446-11ea-8781-2213ef5d6181.png">

**Comment by Morban15** [comment]
![landing-page-header](https://user-images.githubusercontent.com/29107510/81943869-ed466480-95c9-11ea-8c87-e27bdb880598.png)
