### ISSUE TITLE
Add metadata information to the news landing page

### ISSUE THREAD

**Issue by misscs** [cosola-salvia/macile-newsletter#124]
## Objective

Add the necessary metadata information to the landing page

- Page title and description
- Image
- Twitter and Facebook information

## Implementation

- The name of the page is MACILE News
- We don't have a description yet, that is up to the person assigned to come up with something. 
- We don't have an image for the news page yet. I'll post an option for us to use later today.

**Comment by Morban15** [comment]
@misscs 
Can you post the image option?
