### ISSUE TITLE
Traduccion al español

### ISSUE THREAD

**Issue by Morban15** [cosola-salvia/macile-newsletter#19]
- [x] Provide the spanish version of the newsletter @cosola 
- [x] Copiar el `index.html` y cambiar el contenido al español
- [x] Agregar las etiquetas de `meta` para los idiomas 
- [x] Agregar una carpeta `es` y colocar el `index.html`

**Comment by Morban15** [comment]
@cosola, dónde está la información del contenido en español?

**Comment by cosola** [comment]
[July_October_2019Spanish-MACILE-F.pdf](https://github.com/cosola-salvia/macile-newsletter/files/4359661/July_October_2019Spanish-MACILE-F.pdf)

**Comment by misscs** [comment]
Here's the meta tag for langauge 

```
<link rel="alternate" hreflang="es" href="https://www.mozilla.org/es-ES/" title="Español">
```

Before implementing, take a look at whether we can just use `en` and `es` for spanish or if we need to be more specific, ex. `en-US` `es-ES`. 

You can use mozilla.org source code as a reference. I'm sure MDN will have the information you need.

**Comment by misscs** [comment]
@MariaGuillen I do agree with you that we should be okay with `en` and `es` but it would be good to understand a bit more about how internationalization and localization works on the web. Sometimes this is also called **i19n**. 

If you can do a bit more research and upload a comment with yoru findings, I think that would be most helpful for the whole team.
