### ISSUE TITLE
Add section for acknowledgments

### ISSUE THREAD

**Issue by cosola** [cosola-salvia/macile-newsletter#90]
Create section/div to includes acknowledgments in the bulletin

This section will appear on every bulletin page. Acknowledgments are based on the contributors to the time range covered by the bulletin. 

- [ ] Write the content @cosola 
- [ ] Sketch of the section 
- [ ] Implement

**Comment by cosola** [comment]
#90 is also part of issue #75 . For better handling of the coding, I'll consider comments and acknowledgments together in the same branch  
> 75-section-commnets.

**Comment by Morban15** [comment]
@cosola 
Where is the content?
