### ISSUE TITLE
Rename classes 

### ISSUE THREAD

**Issue by cosola** [cosola-salvia/macile-newsletter#92]
Select more meaningful and reusable names for classes

- [x] Lesson on different CSS strategies @misscs 
- [x] Read and learn about the history of various css strategies. Prepare as short description of each one. 
  * OOCSS @lehysen @Morban15 
  * SMACSS @Morban15 
  * Atomic @Morban15
  * Functional @Morban15
  * BEM @lehysen 
- [x] Decide on an approach that we want to take for the newsletter + bulletin
- [x] Rename classes and remove unused css selectors

**Comment by misscs** [comment]
We shouldn't have any IDs in the stylesheets. I updated the issue and title.

**Comment by misscs** [comment]
#### standup 04-05

- Friday @MariaGuillen @Morban15 read up on css methodologies
- Today they plan on discussing and picking a direction

**Comment by misscs** [comment]
#### standup 06-05

* Going to use BEM instead of combing OOCSS + BEM
* Working on analyzing HTML code and writing
