### ISSUE TITLE
Design and implement a landing page for news site

### ISSUE THREAD

**Issue by misscs** [cosola-salvia/macile-newsletter#97]
We need a landing page that allows us to navigate between the newsletter and bulletin. 

It should be a simple list page that is flexible enough to allows us to add another newsletter of bulletin. 

- [x] Define what content we want to see
- [x] Sketch and prototype - BE CREATIVE. BE RADICAL.
- [x] Team feedback and selection
- [x] Implementarlo (redefinir las sub-tareas)

### Page Elements

* Block about MACILE
* Header el logo, menu de idiomas
* Footer
* Donate link (maybe in the header?) to paypal or email

### List item elements

* distinguish bulletin and newsletter
* Titulo del issue links to issue
* Numbero del issue / Volumen o la fecha
* Resumen del issue 
* Imagen/thumbnail del issue
* Read current issue link

**Comment by Morban15** [comment]
![_20200508_073908](https://user-images.githubusercontent.com/29107510/81402305-24ff6900-90ff-11ea-8b61-51b22f0bdba2.JPG)

![_20200508_073836](https://user-images.githubusercontent.com/29107510/81402319-2b8de080-90ff-11ea-9b92-8ce040b24969.JPG)

![_20200508_073802](https://user-images.githubusercontent.com/29107510/81402340-35afdf00-90ff-11ea-9905-fc48ff7f1d95.JPG)

![_20200508_073638](https://user-images.githubusercontent.com/29107510/81402358-3f394700-90ff-11ea-8888-7a545763cccc.JPG)

![_20200508_073434](https://user-images.githubusercontent.com/29107510/81402378-452f2800-90ff-11ea-9ccb-cb90cb77141b.JPG)

![_20200508_073211](https://user-images.githubusercontent.com/29107510/81402390-4bbd9f80-90ff-11ea-810d-d7f557bb3b3a.JPG)

### Bloques para news

![_20200508_074921](https://user-images.githubusercontent.com/29107510/81402822-1d8c8f80-9100-11ea-83a4-a715ee7aa5e9.JPG)

![_20200508_074855](https://user-images.githubusercontent.com/29107510/81402826-21b8ad00-9100-11ea-9a78-900030c72387.JPG)

![_20200508_074830](https://user-images.githubusercontent.com/29107510/81402835-267d6100-9100-11ea-8db4-ee0549f13da2.JPG)

![_20200508_074804](https://user-images.githubusercontent.com/29107510/81402841-2b421500-9100-11ea-93ff-2e39f4d2bc9a.JPG)

**Comment by MariaGuillen** [comment]
![image](https://user-images.githubusercontent.com/29066354/81426728-9a7f2f80-9127-11ea-9a42-fe8fef0a2246.jpeg)
![image](https://user-images.githubusercontent.com/29066354/81426781-ad91ff80-9127-11ea-90e3-d35b7acb3d6d.jpeg)
![image](https://user-images.githubusercontent.com/29066354/81427013-15e0e100-9128-11ea-8be9-5e683039d907.jpeg)
![image](https://user-images.githubusercontent.com/29066354/81438917-8b09e180-913b-11ea-81ea-1aab0fec99bf.jpeg)

**Comment by lehysen** [comment]
#
![20200509_144009](https://user-images.githubusercontent.com/29067344/81482347-5a41af00-9204-11ea-8aa0-1cd73b144de0.jpg)

**Comment by Morban15** [comment]
@misscs @cosola 
Estas son nuestras conclusiones

![_20200511_152032](https://user-images.githubusercontent.com/29107510/81602870-5d22d800-939b-11ea-9286-e25527961917.JPG)

![_20200511_152005](https://user-images.githubusercontent.com/29107510/81602888-657b1300-939b-11ea-9679-34c0d395ad0b.JPG)

**Comment by misscs** [comment]
I think this one is the most interesting design wise

![image](https://user-images.githubusercontent.com/51812/81603995-3a91be80-939d-11ea-896a-bf10c4776a47.png)

However, I think there are a few design elements from the prior designs that would be nice to keep because they were visually interesting

## About MACILE Section

![81402358-3f394700-90ff-11ea-8888-7a545763cccc](https://user-images.githubusercontent.com/51812/81604276-a8d68100-939d-11ea-9535-13d0c7de530b.JPG)

I really like how this design encapsulates the about text. I think it would be more compelling than having a visible section header _About MACILE_ and it would look nice below the logo

## Newsletter/Bulletin Teasers

What goes in the the circle? Is that going to be a thumbnail image or an icon to indicate if it's a bulletin or newsletter?

I recommend removing the _Go_ button. Users on the web are accustomed to clicking titles or images in a teaser to get to the node page. If you want to have an explicit button, then a more exciting call to action should replace _Go_, for example _Read More_ or _Dive in_. _Go_ seems like a race or a video game. 🐎 

Can you expand the teaser to show how you plan on incorporating the required design elements? 

## Donate

I don't think _Donate_ should be a button in the footer, it gets lost. I recommend creating a section after news that's a call to action to donate. It would be far more compelling. This sketch captures the idea of including a separate block, with some text, and the donate button.

![81426728-9a7f2f80-9127-11ea-9a42-fe8fef0a2246](https://user-images.githubusercontent.com/51812/81606313-d3760900-93a0-11ea-939a-b2846cd545c2.jpeg)


## Missing information in the header

This sketch correctly captures how we need to include MACILE in the header. It should include the acronym spelled out.

![81482347-5a41af00-9204-11ea-8aa0-1cd73b144de0](https://user-images.githubusercontent.com/51812/81605633-c278c800-939f-11ea-9b4f-ecf5d38eceac.jpg)

**Comment by Morban15** [comment]
![_20200511_181026](https://user-images.githubusercontent.com/29107510/81617220-0628fd00-93b3-11ea-81a7-c417e1544090.JPG)

**Comment by MariaGuillen** [comment]
![image](https://user-images.githubusercontent.com/29066354/81618898-55246180-93b6-11ea-9704-a955eb04a0d4.jpeg)
![image](https://user-images.githubusercontent.com/29066354/81618908-5d7c9c80-93b6-11ea-9f22-5efb7f86a18d.jpeg)
